// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: iam.proto

package iampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Используется оркестратором: получить данные пользователя по логину.
type GetUserByLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByLoginRequest) Reset() {
	*x = GetUserByLoginRequest{}
	mi := &file_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginRequest) ProtoMessage() {}

func (x *GetUserByLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginRequest.ProtoReflect.Descriptor instead.
func (*GetUserByLoginRequest) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,5,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	IsHead        bool                   `protobuf:"varint,6,opt,name=is_head,json=isHead,proto3" json:"is_head,omitempty"`
	SystemRole    string                 `protobuf:"bytes,7,opt,name=system_role,json=systemRole,proto3" json:"system_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserResponse) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *UserResponse) GetIsHead() bool {
	if x != nil {
		return x.IsHead
	}
	return false
}

func (x *UserResponse) GetSystemRole() string {
	if x != nil {
		return x.SystemRole
	}
	return ""
}

// Используется оркестратором: получить начальников отдела (для назначения визировщика).
type GetManagersByDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int32                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManagersByDepartmentRequest) Reset() {
	*x = GetManagersByDepartmentRequest{}
	mi := &file_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManagersByDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManagersByDepartmentRequest) ProtoMessage() {}

func (x *GetManagersByDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManagersByDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetManagersByDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{2}
}

func (x *GetManagersByDepartmentRequest) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type ManagersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Managers      []*UserResponse        `protobuf:"bytes,1,rep,name=managers,proto3" json:"managers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagersResponse) Reset() {
	*x = ManagersResponse{}
	mi := &file_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagersResponse) ProtoMessage() {}

func (x *ManagersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagersResponse.ProtoReflect.Descriptor instead.
func (*ManagersResponse) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{3}
}

func (x *ManagersResponse) GetManagers() []*UserResponse {
	if x != nil {
		return x.Managers
	}
	return nil
}

// Используется notification-service: получить email пользователя.
type GetUserEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEmailRequest) Reset() {
	*x = GetUserEmailRequest{}
	mi := &file_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEmailRequest) ProtoMessage() {}

func (x *GetUserEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserEmailRequest) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserEmailRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserEmailResponse) Reset() {
	*x = GetUserEmailResponse{}
	mi := &file_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserEmailResponse) ProtoMessage() {}

func (x *GetUserEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserEmailResponse.ProtoReflect.Descriptor instead.
func (*GetUserEmailResponse) Descriptor() ([]byte, []int) {
	return file_iam_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserEmailResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_iam_proto protoreflect.FileDescriptor

const file_iam_proto_rawDesc = "" +
	"\n" +
	"\tiam.proto\x12\x03iam\"-\n" +
	"\x15GetUserByLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"\xc6\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12#\n" +
	"\rdepartment_id\x18\x05 \x01(\x05R\fdepartmentId\x12\x17\n" +
	"\ais_head\x18\x06 \x01(\bR\x06isHead\x12\x1f\n" +
	"\vsystem_role\x18\a \x01(\tR\n" +
	"systemRole\"E\n" +
	"\x1eGetManagersByDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x05R\fdepartmentId\"A\n" +
	"\x10ManagersResponse\x12-\n" +
	"\bmanagers\x18\x01 \x03(\v2\x11.iam.UserResponseR\bmanagers\".\n" +
	"\x13GetUserEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"I\n" +
	"\x14GetUserEmailResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName2\xe9\x01\n" +
	"\n" +
	"IAMService\x12?\n" +
	"\x0eGetUserByLogin\x12\x1a.iam.GetUserByLoginRequest\x1a\x11.iam.UserResponse\x12U\n" +
	"\x17GetManagersByDepartment\x12#.iam.GetManagersByDepartmentRequest\x1a\x15.iam.ManagersResponse\x12C\n" +
	"\fGetUserEmail\x12\x18.iam.GetUserEmailRequest\x1a\x19.iam.GetUserEmailResponseB Z\x1edocflow.local/pkg/pb/iam;iampbb\x06proto3"

var (
	file_iam_proto_rawDescOnce sync.Once
	file_iam_proto_rawDescData []byte
)

func file_iam_proto_rawDescGZIP() []byte {
	file_iam_proto_rawDescOnce.Do(func() {
		file_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)))
	})
	return file_iam_proto_rawDescData
}

var file_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_iam_proto_goTypes = []any{
	(*GetUserByLoginRequest)(nil),          // 0: iam.GetUserByLoginRequest
	(*UserResponse)(nil),                   // 1: iam.UserResponse
	(*GetManagersByDepartmentRequest)(nil), // 2: iam.GetManagersByDepartmentRequest
	(*ManagersResponse)(nil),               // 3: iam.ManagersResponse
	(*GetUserEmailRequest)(nil),            // 4: iam.GetUserEmailRequest
	(*GetUserEmailResponse)(nil),           // 5: iam.GetUserEmailResponse
}
var file_iam_proto_depIdxs = []int32{
	1, // 0: iam.ManagersResponse.managers:type_name -> iam.UserResponse
	0, // 1: iam.IAMService.GetUserByLogin:input_type -> iam.GetUserByLoginRequest
	2, // 2: iam.IAMService.GetManagersByDepartment:input_type -> iam.GetManagersByDepartmentRequest
	4, // 3: iam.IAMService.GetUserEmail:input_type -> iam.GetUserEmailRequest
	1, // 4: iam.IAMService.GetUserByLogin:output_type -> iam.UserResponse
	3, // 5: iam.IAMService.GetManagersByDepartment:output_type -> iam.ManagersResponse
	5, // 6: iam.IAMService.GetUserEmail:output_type -> iam.GetUserEmailResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_iam_proto_init() }
func file_iam_proto_init() {
	if File_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_proto_rawDesc), len(file_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_proto_goTypes,
		DependencyIndexes: file_iam_proto_depIdxs,
		MessageInfos:      file_iam_proto_msgTypes,
	}.Build()
	File_iam_proto = out.File
	file_iam_proto_goTypes = nil
	file_iam_proto_depIdxs = nil
}
