// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Используется оркестратором: получить мета-данные документа.
type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocumentRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,4,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	CreatedBy     int32                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	AssigneeId    int32                  `protobuf:"varint,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DocumentResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DocumentResponse) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *DocumentResponse) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *DocumentResponse) GetAssigneeId() int32 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

func (x *DocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Используется оркестратором: сменить ответственного по документу.
type ChangeAssigneeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	NewAssigneeId int32                  `protobuf:"varint,2,opt,name=new_assignee_id,json=newAssigneeId,proto3" json:"new_assignee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAssigneeRequest) Reset() {
	*x = ChangeAssigneeRequest{}
	mi := &file_proto_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAssigneeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAssigneeRequest) ProtoMessage() {}

func (x *ChangeAssigneeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAssigneeRequest.ProtoReflect.Descriptor instead.
func (*ChangeAssigneeRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeAssigneeRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *ChangeAssigneeRequest) GetNewAssigneeId() int32 {
	if x != nil {
		return x.NewAssigneeId
	}
	return 0
}

type ChangeAssigneeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeAssigneeResponse) Reset() {
	*x = ChangeAssigneeResponse{}
	mi := &file_proto_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeAssigneeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeAssigneeResponse) ProtoMessage() {}

func (x *ChangeAssigneeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeAssigneeResponse.ProtoReflect.Descriptor instead.
func (*ChangeAssigneeResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeAssigneeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Используется оркестратором: обновить статус FSM документа.
type UpdateDocumentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentStatusRequest) Reset() {
	*x = UpdateDocumentStatusRequest{}
	mi := &file_proto_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentStatusRequest) ProtoMessage() {}

func (x *UpdateDocumentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDocumentStatusRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *UpdateDocumentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateDocumentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentStatusResponse) Reset() {
	*x = UpdateDocumentStatusResponse{}
	mi := &file_proto_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentStatusResponse) ProtoMessage() {}

func (x *UpdateDocumentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDocumentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSystemFolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int32                  `protobuf:"varint,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemFolderRequest) Reset() {
	*x = GetSystemFolderRequest{}
	mi := &file_proto_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemFolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemFolderRequest) ProtoMessage() {}

func (x *GetSystemFolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemFolderRequest.ProtoReflect.Descriptor instead.
func (*GetSystemFolderRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetSystemFolderRequest) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *GetSystemFolderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FolderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsSystem      bool                   `protobuf:"varint,4,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderResponse) Reset() {
	*x = FolderResponse{}
	mi := &file_proto_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderResponse) ProtoMessage() {}

func (x *FolderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderResponse.ProtoReflect.Descriptor instead.
func (*FolderResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *FolderResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FolderResponse) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *FolderResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FolderResponse) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

type MoveDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    int32                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	FolderId      int32                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	ActorLogin    string                 `protobuf:"bytes,3,opt,name=actor_login,json=actorLogin,proto3" json:"actor_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveDocumentRequest) Reset() {
	*x = MoveDocumentRequest{}
	mi := &file_proto_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDocumentRequest) ProtoMessage() {}

func (x *MoveDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDocumentRequest.ProtoReflect.Descriptor instead.
func (*MoveDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *MoveDocumentRequest) GetDocumentId() int32 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *MoveDocumentRequest) GetFolderId() int32 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *MoveDocumentRequest) GetActorLogin() string {
	if x != nil {
		return x.ActorLogin
	}
	return ""
}

type MoveDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveDocumentResponse) Reset() {
	*x = MoveDocumentResponse{}
	mi := &file_proto_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDocumentResponse) ProtoMessage() {}

func (x *MoveDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDocumentResponse.ProtoReflect.Descriptor instead.
func (*MoveDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *MoveDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\x13proto/catalog.proto\x12\acatalog\"5\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\"\xd2\x01\n" +
	"\x10DocumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12#\n" +
	"\rdepartment_id\x18\x04 \x01(\x05R\fdepartmentId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x05R\tcreatedBy\x12\x1f\n" +
	"\vassignee_id\x18\x06 \x01(\x05R\n" +
	"assigneeId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"`\n" +
	"\x15ChangeAssigneeRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\x12&\n" +
	"\x0fnew_assignee_id\x18\x02 \x01(\x05R\rnewAssigneeId\"2\n" +
	"\x16ChangeAssigneeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x1bUpdateDocumentStatusRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"8\n" +
	"\x1cUpdateDocumentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x16GetSystemFolderRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\x05R\fdepartmentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"v\n" +
	"\x0eFolderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\x05R\fdepartmentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_system\x18\x04 \x01(\bR\bisSystem\"t\n" +
	"\x13MoveDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x05R\n" +
	"documentId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x05R\bfolderId\x12\x1f\n" +
	"\vactor_login\x18\x03 \x01(\tR\n" +
	"actorLogin\"0\n" +
	"\x14MoveDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb1\x03\n" +
	"\x0eCatalogService\x12E\n" +
	"\vGetDocument\x12\x1b.catalog.GetDocumentRequest\x1a\x19.catalog.DocumentResponse\x12Y\n" +
	"\x16ChangeDocumentAssignee\x12\x1e.catalog.ChangeAssigneeRequest\x1a\x1f.catalog.ChangeAssigneeResponse\x12c\n" +
	"\x14UpdateDocumentStatus\x12$.catalog.UpdateDocumentStatusRequest\x1a%.catalog.UpdateDocumentStatusResponse\x12K\n" +
	"\x0fGetSystemFolder\x12\x1f.catalog.GetSystemFolderRequest\x1a\x17.catalog.FolderResponse\x12K\n" +
	"\fMoveDocument\x12\x1c.catalog.MoveDocumentRequest\x1a\x1d.catalog.MoveDocumentResponseB(Z&docflow.local/pkg/pb/catalog;catalogpbb\x06proto3"

var (
	file_proto_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_proto_rawDescData []byte
)

func file_proto_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_proto_rawDesc), len(file_proto_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_proto_rawDescData
}

var file_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_catalog_proto_goTypes = []any{
	(*GetDocumentRequest)(nil),           // 0: catalog.GetDocumentRequest
	(*DocumentResponse)(nil),             // 1: catalog.DocumentResponse
	(*ChangeAssigneeRequest)(nil),        // 2: catalog.ChangeAssigneeRequest
	(*ChangeAssigneeResponse)(nil),       // 3: catalog.ChangeAssigneeResponse
	(*UpdateDocumentStatusRequest)(nil),  // 4: catalog.UpdateDocumentStatusRequest
	(*UpdateDocumentStatusResponse)(nil), // 5: catalog.UpdateDocumentStatusResponse
	(*GetSystemFolderRequest)(nil),       // 6: catalog.GetSystemFolderRequest
	(*FolderResponse)(nil),               // 7: catalog.FolderResponse
	(*MoveDocumentRequest)(nil),          // 8: catalog.MoveDocumentRequest
	(*MoveDocumentResponse)(nil),         // 9: catalog.MoveDocumentResponse
}
var file_proto_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.CatalogService.GetDocument:input_type -> catalog.GetDocumentRequest
	2, // 1: catalog.CatalogService.ChangeDocumentAssignee:input_type -> catalog.ChangeAssigneeRequest
	4, // 2: catalog.CatalogService.UpdateDocumentStatus:input_type -> catalog.UpdateDocumentStatusRequest
	6, // 3: catalog.CatalogService.GetSystemFolder:input_type -> catalog.GetSystemFolderRequest
	8, // 4: catalog.CatalogService.MoveDocument:input_type -> catalog.MoveDocumentRequest
	1, // 5: catalog.CatalogService.GetDocument:output_type -> catalog.DocumentResponse
	3, // 6: catalog.CatalogService.ChangeDocumentAssignee:output_type -> catalog.ChangeAssigneeResponse
	5, // 7: catalog.CatalogService.UpdateDocumentStatus:output_type -> catalog.UpdateDocumentStatusResponse
	7, // 8: catalog.CatalogService.GetSystemFolder:output_type -> catalog.FolderResponse
	9, // 9: catalog.CatalogService.MoveDocument:output_type -> catalog.MoveDocumentResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_catalog_proto_init() }
func file_proto_catalog_proto_init() {
	if File_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_proto_rawDesc), len(file_proto_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_proto = out.File
	file_proto_catalog_proto_goTypes = nil
	file_proto_catalog_proto_depIdxs = nil
}
