# syntax=docker/dockerfile:1
# Build context: Backend/

FROM gradle:8.7-jdk17 AS builder
WORKDIR /workspace
# Копируем proto + сервис
COPY proto/ proto/
COPY java-services/file-service/ java-services/file-service/
WORKDIR /workspace/java-services/file-service
RUN gradle installDist --no-daemon -x test

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /workspace/java-services/file-service/build/install/file-service/ .
ENTRYPOINT ["./bin/file-service"]
